language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ionic-gulp' ]; then cd .. && eval "mv $currentfolder generator-ionic-gulp" && cd generator-ionic-gulp; fi
